# Generated by Django 4.2.7 on 2025-08-01 10:47

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (RU)"
                    ),
                ),
                (
                    "name_he",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (HE)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="Description (HE)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Color"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (RU)"
                    ),
                ),
                (
                    "name_he",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (HE)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="Description (HE)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0%"),
                            (10, "10%"),
                            (20, "20%"),
                            (30, "30%"),
                            (40, "40%"),
                            (50, "50%"),
                            (60, "60%"),
                            (70, "70%"),
                            (80, "80%"),
                            (90, "90%"),
                            (100, "100%"),
                        ],
                        default=0,
                        verbose_name="Level",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("database", "Database"),
                            ("devops", "DevOps"),
                            ("design", "Design"),
                            ("soft", "Soft Skills"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["category", "position"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="Description (HE)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.get_image_upload_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Color"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "version",
                    models.CharField(blank=True, max_length=20, verbose_name="Version"),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(blank=True, verbose_name="Meta Keywords"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured"),
                ),
                (
                    "featured_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Featured Order"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (RU)"
                    ),
                ),
                (
                    "title_he",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (HE)"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subtitle (EN)"
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subtitle (RU)"
                    ),
                ),
                (
                    "subtitle_he",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subtitle (HE)"
                    ),
                ),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="Description (HE)"),
                ),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Content (EN)"),
                ),
                (
                    "content_ru",
                    models.TextField(blank=True, verbose_name="Content (RU)"),
                ),
                (
                    "content_he",
                    models.TextField(blank=True, verbose_name="Content (HE)"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=apps.core.models.get_image_upload_path,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.get_image_upload_path,
                        verbose_name="Cover Image",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Client Name"
                    ),
                ),
                (
                    "client_website",
                    models.URLField(blank=True, verbose_name="Client Website"),
                ),
                (
                    "project_url",
                    models.URLField(blank=True, verbose_name="Project URL"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_ongoing",
                    models.BooleanField(default=False, verbose_name="Is Ongoing"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="projects",
                        to="portfolio.category",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projects",
                        to="portfolio.technology",
                        verbose_name="Technologies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-published_at", "order"],
            },
        ),
    ]
