# Generated by Django 4.2.7 on 2025-08-01 10:47

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("bio_en", models.TextField(blank=True, verbose_name="Bio (EN)")),
                ("bio_ru", models.TextField(blank=True, verbose_name="Bio (RU)")),
                ("bio_he", models.TextField(blank=True, verbose_name="Bio (HE)")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Location"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Русский"), ("he", "עברית")],
                        default="en",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.get_image_upload_path,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "job_title_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Job Title (EN)"
                    ),
                ),
                (
                    "job_title_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Job Title (RU)"
                    ),
                ),
                (
                    "job_title_he",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Job Title (HE)"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Company"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Telegram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "is_available_for_hire",
                    models.BooleanField(
                        default=True, verbose_name="Available for Hire"
                    ),
                ),
                (
                    "show_email_publicly",
                    models.BooleanField(
                        default=False, verbose_name="Show Email Publicly"
                    ),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Receive Notifications"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
