# Generated by Django 4.2.7 on 2025-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("about", "About Page"),
                            ("portfolio", "Portfolio Page"),
                            ("blog", "Blog Page"),
                            ("contact", "Contact Page"),
                            ("resume", "Resume Page"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Page Type",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=60, verbose_name="Title (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Title (RU)"
                    ),
                ),
                (
                    "title_he",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Title (HE)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(max_length=160, verbose_name="Description (EN)"),
                ),
                (
                    "description_ru",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Description (RU)"
                    ),
                ),
                (
                    "description_he",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Description (HE)"
                    ),
                ),
                (
                    "keywords_en",
                    models.TextField(blank=True, verbose_name="Keywords (EN)"),
                ),
                (
                    "keywords_ru",
                    models.TextField(blank=True, verbose_name="Keywords (RU)"),
                ),
                (
                    "keywords_he",
                    models.TextField(blank=True, verbose_name="Keywords (HE)"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/", verbose_name="OG Image"
                    ),
                ),
                (
                    "og_type",
                    models.CharField(
                        default="website", max_length=20, verbose_name="OG Type"
                    ),
                ),
                (
                    "schema_markup",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Schema Markup"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
                "ordering": ["page_type"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "site_name_en",
                    models.CharField(max_length=100, verbose_name="Site Name (EN)"),
                ),
                (
                    "site_name_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Site Name (RU)"
                    ),
                ),
                (
                    "site_name_he",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Site Name (HE)"
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tagline (EN)"
                    ),
                ),
                (
                    "tagline_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tagline (RU)"
                    ),
                ),
                (
                    "tagline_he",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tagline (HE)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="Description (HE)"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "address_en",
                    models.TextField(blank=True, verbose_name="Address (EN)"),
                ),
                (
                    "address_ru",
                    models.TextField(blank=True, verbose_name="Address (RU)"),
                ),
                (
                    "address_he",
                    models.TextField(blank=True, verbose_name="Address (HE)"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Telegram URL"),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Maintenance Mode"),
                ),
                (
                    "maintenance_message_en",
                    models.TextField(
                        blank=True, verbose_name="Maintenance Message (EN)"
                    ),
                ),
                (
                    "maintenance_message_ru",
                    models.TextField(
                        blank=True, verbose_name="Maintenance Message (RU)"
                    ),
                ),
                (
                    "maintenance_message_he",
                    models.TextField(
                        blank=True, verbose_name="Maintenance Message (HE)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "yandex_metrica_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Yandex Metrica ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
